### ISSUE TITLE
The link doesn’t work.

### ISSUE THREAD

**Issue by caiosweet** [gpirrotta/protezionecivilepop#5]
Ciao. Bellissima ed utilissima applicazione.
Ho inserito i dati da json in homeassistat (Hass.io) e ho notato che il link generato dal file json, porta alla home del sito Dipartimento di Protezione Civile.
Quello che noto è che è differente da
[http://www.protezionecivile.gov.it/attivita-rischi/meteo-idro/attivita/previsione-prevenzione/centro-funzionale-centrale-rischio-meteo-idrogeologico/previsionale/bollettini-criticita/bollettino-odierno](url)

a questo generato che porta alla home...
[http://www.protezionecivile.gov.it/jcms/it/bollettini_di_criticita.wp?folignoidrogeologico20190902](url)

Sarebbe interessante fare un custom component con HomeAssistant, ma ho letto che hai dovuto ricorrere allo scraping, è cambiato qualcosa nel frattempo?

Volendo usare direttamente le API, hai qualche suggerimento per trovare il codice istat in base alla geolocalizzazione?

Grazie in anticipo

**Comment by caiosweet** [comment]
Ok, sono riuscito ad integrare con un custom component (anche se si può utilizzare il sensore restFull, con il componente personalizzato si possono fare più cose...) le allerte della Protezione Civile in Home-Assistant, con la geolocalizzazione per il numero ISTAT.
Come informazione e fonte dati cosa dovrei mettere?
Information provided by protezionecivilepop.tk o della ProtezioneCivile? :0)

**Comment by gpirrotta** [comment]
Ciao, 

> Ok, sono riuscito ad integrare con un custom component (anche se si può utilizzare il sensore restFull, con il componente personalizzato si possono fare più cose...) le allerte della Protezione Civile in Home-Assistant, con la geolocalizzazione per il numero ISTAT.
> Come informazione e fonte dati cosa dovrei mettere?
> Information provided by protezionecivilepop.tk o della ProtezioneCivile? :0)

come indicazione per la licenza d'uso devi indicare l'autore, il link al progetto, il tipo di licenza e il link alla licenza.
**Es.**
Dati forniti dal servizio [protezionecivilepop.tk](http://www.protezionecivilepop.tk/) di Giovanni Pirrotta -  Licenza Creative Commons [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.it).

ciao
