### ISSUE TITLE
Missing data ("previsione":) i.e. Bologna

### ISSUE THREAD

**Issue by caiosweet** [gpirrotta/protezionecivilepop#8]
Hi Pirrotta, there are problems in the data request 
Missing data (previsione":) for some cities, for example Bologna, see here
http://www.protezionecivilepop.tk/allerte?citta=037006&rischio=idraulico&allerta=verde&giorno=oggi&formato=json

http://www.protezionecivile.gov.it/geoserver/bcr/shp/20210110_1443_shp.zip

for example here everything is ok...
http://www.protezionecivilepop.tk/allerte?citta=058091&rischio=idraulico&allerta=verde&giorno=oggi&formato=json

Thanks in advance

**Comment by gpirrotta** [comment]
The Protezione Civile changed some area codes. I updates the codes and not it works.
Thank-you for your feedback.

GP
